# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apt:
      repo: puppetlabs/apt
      ref: 8.3.0
    concat:
      repo: "puppetlabs/concat"
      ref: "7.1.1"
    puppet_agent:
      repo: "puppetlabs/puppet_agent"
      ref: "4.9.0"
    selinux:
      repo: "puppet/selinux"
      ref: "3.4.1"
    selinux_core:
      repo: puppetlabs/selinux_core
      puppet_version: ">= 6.0.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "8.1.0"
    systemd:
      repo: "puppet/systemd"
      ref: "3.5.1"
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      puppet_version: ">= 6.0.0"
  repositories:
    lsys:
      repo: https://github.com/aursu/puppet-lsys.git
      ref: tags/v0.24.3
    nginx:
      repo: https://github.com/aursu/puppet-nginx.git
      ref: tags/v3.3.1-rc0.4
    puppet:
      repo: https://github.com/aursu/puppet-puppet.git
    tlsinfo:
      repo: https://github.com/aursu/puppet-tlsinfo.git
