# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apt:
      repo: puppetlabs/apt
      ref: 9.1.0
    concat:
      repo: puppetlabs/concat
      ref: 9.0.0
    lsys:
      repo: aursu/lsys
      ref: 0.46.0
    nginx:
      repo: aursu/nginx
      ref: 4.4.2
    puppet_agent:
      repo: puppetlabs/puppet_agent
      ref: 4.14.0
    selinux:
      repo: puppet/selinux
      ref: 4.0.0
    selinux_core:
      repo: puppetlabs/selinux_core
      puppet_version: ">= 6.0.0"
    stdlib:
      repo: puppetlabs/stdlib
      ref: 9.3.0
    systemd:
      repo: puppet/systemd
      ref: 6.0.0
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      puppet_version: ">= 6.0.0"
  repositories:
    puppet:
      repo: https://github.com/aursu/puppet-puppet.git
      ref: tags/v0.7.1
    tlsinfo:
      repo: https://github.com/aursu/puppet-tlsinfo.git
      ref: tags/v0.3.7
