# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apt:
      repo: puppetlabs/apt
      ref: 9.1.0
    bsys:
      repo: aursu/bsys
      ref: 0.4.0
    concat:
      repo: puppetlabs/concat
      ref: 9.0.0
    lsys_nginx:
      repo: aursu/lsys_nginx
      ref: 0.47.0
    nginx:
      repo: aursu/nginx
      ref: 4.4.2
    puppet_agent:
      repo: puppetlabs/puppet_agent
      ref: 4.14.0
    selinux:
      repo: puppet/selinux
      ref: 4.0.0
    selinux_core:
      repo: puppetlabs/selinux_core
    stdlib:
      repo: puppetlabs/stdlib
      ref: 9.7.0
    systemd:
      repo: puppet/systemd
      ref: 7.1.0
    tlsinfo:
      repo: aursu/tlsinfo
      ref: 0.5.0
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
  repositories:
    puppet:
      repo: https://github.com/aursu/puppet-puppet.git
      ref: "tags/v0.30.4"
